//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class assignment
{
    public int AssignmentId { get; set; }
    public string AssignmentName { get; set; }
    public int Type { get; set; }
    public System.DateTime SubDate { get; set; }
    public int CourseId { get; set; }

    public virtual assignment assignment1 { get; set; }
    public virtual assignment assignment2 { get; set; }
    public virtual Cours Cours { get; set; }
}

public partial class Cours
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cours()
    {
        this.assignments = new HashSet<assignment>();
        this.enrolleds = new HashSet<enrolled>();
        this.grades = new HashSet<grade>();
    }

    public int CourseId { get; set; }
    public string CourseName { get; set; }
    public int TeacherId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<assignment> assignments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<enrolled> enrolleds { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<grade> grades { get; set; }
}

public partial class enrolled
{
    public int UserId { get; set; }
    public int CourseId { get; set; }

    public virtual Cours Cours { get; set; }
    public virtual enrolled enrolled1 { get; set; }
    public virtual enrolled enrolled2 { get; set; }
    public virtual User User { get; set; }
}

public partial class grade
{
    public int AssignmentId { get; set; }
    public int UserId { get; set; }
    public int CourseId { get; set; }
    public Nullable<int> Grade1 { get; set; }

    public virtual Cours Cours { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.enrolleds = new HashSet<enrolled>();
        this.grades = new HashSet<grade>();
    }

    public int UserId { get; set; }
    public string FirstName { get; set; }
    public string Lastname { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public int Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<enrolled> enrolleds { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<grade> grades { get; set; }
}
