//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class assignment
{
    public int CourseID { get; set; }
    public string assignment1 { get; set; }
    public string Type { get; set; }
    public Nullable<int> year { get; set; }
    public string semester { get; set; }
    public string SubDate { get; set; }
}

public partial class Cours
{
    public int CourseID { get; set; }
    public string CourseName { get; set; }
}

public partial class Grade
{
    public string StudentID { get; set; }
    public int CourseID { get; set; }
    public string AssignmentName { get; set; }
    public int Grade1 { get; set; }
}

public partial class User
{
    public int UserId { get; set; }
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
}
